### ISSUE TITLE
click warnings with python 3 (using docker-compose)

### ISSUE THREAD

**Issue by robdennis** [robdennis/ship_it#17]
```
0700077482A:container-store robert.dennis$ docker-compose run jenkins ship_it manifest.yaml
Traceback (most recent call last):
  File "/usr/bin/ship_it", line 11, in <module>
    sys.exit(main())
  File "/usr/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/click/core.py", line 676, in main
    _verify_python3_env()
  File "/usr/lib/python3.6/site-packages/click/_unicodefun.py", line 118, in _verify_python3_env
    'for mitigation steps.' + extra)
RuntimeError: Click will abort further execution because Python 3 was configured to use ASCII as encoding for the environment.  Consult http://click.pocoo.org/python3/for mitigation steps.

This system lists a couple of UTF-8 supporting locales that
you can pick from.  The following suitable locales where
discovered: en_US.utf8
0700077482A:container-st
```

We could move over to [argparse](https://docs.python.org/3/library/argparse.html), but since @jawnb added click as part #11, I'm wondering if this is something you ran into?

**Comment by ftobia** [comment]
I've seen this recently, this is a consequence of some of Click's design choices (see the url in the error message: http://click.pocoo.org/python3/)

Since apparently your base image has a suitable locale defined, the fix is to include these lines in your Dockerfile:

    ENV LANG=en_US.UTF-8
    ENV LC_ALL=en_US.UTF-8

Since this is more of a click / environment issue than a ship_it issue I suggest that this issue can be closed.

**Comment by jawnb** [comment]
Seconding what @ftobia has to say.


We use python3 exclusively  and set lang to utf8, and haven't had a problem.
